server:
  port: 8090
security:
  basic:
    enabled: false
spring:
  datasource:
    url: jdbc:h2:file:./main.db
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console:
      path: /h2
      settings.trace: false
      settings.web-allow-others: false